### PR TITLE
Support configuring which keys are used for tag & values

### PR DESCRIPTION
**Pull request by LiamGoodacre**
Depends on https://github.com/purescript-contrib/purescript-argonaut-generic/pull/11
Not tied to the names, feel free to suggest better ones.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
@LiamGoodacre Would you mind explaining a little about the motivation behind this change? 

I understand this allows for choosing what keys to use for tag / values, but I'm not sure what new flexibility that opens up.

**Comment by thomashoneyman** [comment]
I inadvertently merged this as I thought I was looking at the simple dependency update. It's been merged and then reverted in master. I'd like to continue this conversation briefly before merging officially, if you don't mind. Sorry about that!

**Comment by thomashoneyman** [comment]
This can be cherry-picked into master when ready. Thanks!

**Comment by LiamGoodacre** [comment]
No problem!  My motivation for this is to interoperate with an existing (fixed) JSON structure that uses different keys than `tag` and `values`.  I didn't want to reimplement all of this just with different keys.

**Comment by thomashoneyman** [comment]
What do you think of supporting both options -- continue allowing a default that uses `tag` and `values`, in a type class member `decodeRep`, which relies on the other type class member, `decodeRepWith`? That would allow current users to continue using their code as-is in a new version without having to update everything with new explicit encodings.

```purescript
class DecodeRep r where
  decodeRep :: Json -> Either String r
  decodeRepWith :: Encoding -> Json -> Either String r

decodeRep = decodeRepWith defaultEncoding
```

**Comment by LiamGoodacre** [comment]
Happy to also have `decodeRep` - but I'm wondering if we should export it separately without it being a type class member?

**Comment by thomashoneyman** [comment]
Thanks for re-opening the PR. I was thinking the same thing.

**Pull request merged**
