### PR TITLE
Handle nested records

### PR DESCRIPTION
**Pull request by paluh**
## What does this pull request do?

It introduces additional instances which handles nested records encoding / decoding.

## Where should the reviewer start?

By reading updated test case scenario: https://github.com/paluh/purescript-argonaut-generic/commit/585ac754c2b0831094e63da535c748975ce2e3a8#diff-5c368d88df5877d784d9953b4281ac87R54

Two instances which are introduced by this PR are nearly exact copies of previously existing instances (https://github.com/paluh/purescript-argonaut-generic/commit/585ac754c2b0831094e63da535c748975ce2e3a8#diff-fdc5c38e890eb2d992cb507448e4ce91R114 and https://github.com/paluh/purescript-argonaut-generic/commit/585ac754c2b0831094e63da535c748975ce2e3a8#diff-ebb87c1312089297047ea2ca2352c648R92)

## How should this be manually tested?

It shouldn't. I've updated test suite.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Hey @paluh! Thanks for adding this functionality; it's nice to see instance chains in use. 

I double-checked with the current implementation and it looks like previously you couldn't use `genericEncodeJson` or `genericDecodeJson` with nested records at all. This seems like a totally reasonable use case.

I'd like to take a day to see if @garyb has anything to add, but if not, then I'll go ahead and merge this.

Thanks again!

**Comment by garyb** [comment]
I have no opinion really, so sure :smile: (I don't use this library or foresee doing so in the future, I guess I shouldn't really be listed explicitly as a maintainer)

**Comment by paluh** [comment]
Thanks for quick response @thomashoneyman!

I probably should reformat some lines. I can provide this additional fixes if needed.

**Comment by paluh** [comment]
@garyb, out of curiosity - if you have to process some json do you write all `EndcodeJson` and `DecodeJson` instances by hand? If so why? Do you consider generic solution to be too inefficient?

**Comment by garyb** [comment]
I/we use https://github.com/garyb/purescript-codec-argonaut, which yeah amounts to writing them by hand pretty much, more explicitly so than using the `EncodeJson` / `DecodeJson` instances even.

It's not due to performance considerations though, it's to prevent inadvertently breaking serialization formats by changing types - I wrote up some notes on it a little while ago: http://code.slipthrough.net/2018/03/13/thoughts-on-typeclass-codecs/. The library provides a few helpers that allow old formats to be "upgraded" during decoding too, although I have some more ideas I want to try there yet.

**Comment by paluh** [comment]
@garyb Thanks a lot for feedback and for the link! Great post!

I wonder what would be your thoughts about generic coding/decoding if case of API with Purescript on both sides (this is our scenario - client / server in PS). For sure this can be a problem when we open up our API, but if we consider it to be "internal"... What do you think?

**Comment by thomashoneyman** [comment]
That's a great post, Gary! If you'd like, I can change the readme so you aren't listed as an explicit maintainer.

Design issues aside, this seems like a great addition for those times when generic encoding / decoding is wanted @paluh and so once you've re-formatted I'll go ahead and merge.

**Comment by garyb** [comment]
@paluh you know, that never occurred to me at all. Perhaps because it seems like too magical a world to be real. :smile:

Really though, personally I wouldn't mind using the `Codec` stuff if this didn't exist - it's definitely quicker to derive them, but I don't find myself spending a great deal of time on writing the codecs either. Although it's boilerplate, that you can't really get it wrong. It's error prone writing the instances by hand, but if the codecs are constructed with the combinators the library provides it's guaranteed to roundtrip, at least.

@thomashoneyman if you don't mind taking over full review duties for this, yes please. I don't want to hold things up if people are finding value in the library just because it's low on my personal list of things to review, etc.

**Comment by thomashoneyman** [comment]
@paluh If you're ready for me to merge, I can go for it!

**Comment by paluh** [comment]
@thomashoneyman Sorry for delay. I've more changes to discuss, but I'm not able to find any spare time... I will try to fix this formatting later today.

**Comment by paluh** [comment]
@thomashoneyman I've found two strategies of formatting instance declarations:

* new line before `::` : https://github.com/purescript-contrib/purescript-argonaut-generic/blob/master/src/Data/Argonaut/Decode/Generic/Rep.purs#L170

* new line after `::`: https://github.com/purescript-contrib/purescript-argonaut-generic/blob/master/src/Data/Argonaut/Decode/Generic/Rep.purs#L72

Which one should I use?

**Comment by thomashoneyman** [comment]
@paluh I believe the newline before `::` is used when there are no parentheses for constraints and newline after `::` is used when there's a large parentheses block. Given your additions have a lot of constraints, I'd say stick with newline after `::`.

**Comment by thomashoneyman** [comment]
@paluh If you don't mind updating this with the conflicting files here, I'll merge straight away. Thanks!

**Comment by paluh** [comment]
@thomashoneyman I'm closing this because it is not needed anymore. I'm going to provide separate PR with test for nested records.

**Pull request closed without merging**
